### ISSUE TITLE
Can you please share the circuit schematics for this Bike.

### ISSUE THREAD

**Issue by 13Titan** [remrc/Reaction-Wheel-Bike#2]
I couldnt get my hands on a Nidec motor so i am using a Gimbal motor along with the AS5048A SPI Encoder and BGC 3.1 but I am new to BGC and dont know where to connect the SPI, Please Help.

**Comment by remrc** [comment]
I don't have a schematic. I always do without a schematic, because it is not needed at all. All connections are described at the beginning of the program. BGC 3.1 has atmega328, so you need to look in the datasheet where the SPI must be connected.
