### ISSUE TITLE
Alternate board for BGC

### ISSUE THREAD

**Issue by dhanushmeda** [remrc/Reaction-Wheel-Bike#3]
Are there any alternatives for this board? Cant find this one in India! Is FOC Shield good enough for this purpose?

**Comment by remrc** [comment]
There are no alternatives. But you can buy it on Aliexpress or Ebay. I used this board for only one reason - it has a microcontroller and two BLDC drivers and is small. By the way, you can use Arduino and FOC Shields, but all this will take up a lot more space.

**Comment by dhanushmeda** [comment]
I was trying to build bgc board on my own, I need some help because there is no documentation. Along with Atmega328p, CP2102X(USB to Serial), I2C hardware, hardware for SPI, BJT's for driving motors, what else do we need to make brushless motors run? what are the BLDC drivers? I really need someone's help with this. Thanks in advance.

**Comment by remrc** [comment]
Doing BGC 3.1 yourself is a bad idea. It costs only ~$15. Two SimpleFOC mini drivers could also be used.

**Comment by dhanushmeda** [comment]
I am not able to get it in India that's why thought of designing, need to try ebay or AliExpress for delivery to India then

**Comment by dhanushmeda** [comment]
I got a BGC board.
I am using arduino ide and i have set the board as arduino nano.
I'm getting the below error.

avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0xc7
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0xc7
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0xc7
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0xc7
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0xc7
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0xc7
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0xc7
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0xc7
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0xc7
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0xc7

**Comment by remrc** [comment]
Probably no bootloader. Ask google how to write a bootloader to atmega328. It's easy, but still requires a bit more knowledge...
